# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Adam DENG's blog
google_analytics: Adam DENG
title: Adam DENG

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Adam DENG's blog

description: Adam DENG's blog
author:
  name: Adam DENG's blog
  email: adamdeng@adam.n.d.deng@gmail.com
  github: cbfmai
  twitter: cbfmai
  pinterest: cbfmai
  linkedin: cbfmai
  bio: A back-end developer!
  email_md5: 2875efb0f287ab5ea51dc5b892128d37

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH: https://cbfmai.github.io/java-tutorial
# BASE_PATH:
gems:
  - jekyll-paginate
